dist: xenial
language: java

before_install:
  - chmod +x gradlew

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
  - compile
  - test
  - name: deploy
    if: tag IS present AND type = push

jobs:
  include:
    - stage: compile
      script: gradle build

    - stage: test
      script: gradle test

    - stage: deploy
      script:
        - sed -i "/plugins {/a\    id \'maven\'" build.gradle
        - |
          cat << EOF >> build.gradle
            def artifactId = 'InvMenu'
            uploadArchives {
                repositories {
                    mavenDeployer {
                        repository(url: "file://$HOME/maven-repo/repository")
                    }
                }
            }
        - git clone https://hhwon:$GITHUB_TOKEN@github.com/ImyvmCircle/maven-repo.git $HOME/maven-repo
        - ./gradlew uploadArchives
        - |
          version=$(gradle properties -q | grep "version:" | awk '{print $2}') &&
          pushd $HOME/maven-repo &&
          git add . &&
          git commit -m "InvMenu $version" &&
          git push origin master &&
          popd

deploy:
  provider: releases
  api_key:
    secure: RxeWz72BYrfAdKogRc5SUetHGVFux/K8mZuL/33Q1IUls39UEWh6aoyU/szp8m0sncX0gEoeHtgcX5JzuaKW0m5rWq69NwkuWkYPtSnj37Uh/xBPVqTTit5+ziu9gaf8RFQtHdygyatGfB/h6aNRwSlzGNATlVUYbLSm0HlTpJplb/BLhbJ9IlIdAFRYPvZMjXdSwb0eBqhU/nFGgFBc8pqgz0+S86trXqM5SARS4lvTeiZ9fOA4B7SXEzknvAkODzR19jOslDkvBXWx8sYe0zeqYafMmdVZ4Dqnj5t4a1uOaJ5mpPinvBN4HIF74BRZ6pxar3QFEy3o7fBdTlyVU6pElnxRZS5fCpEw2mhoIyPLgoDUEbM4mxvugLjM41Snov1uTfEH6NZZb+XeguXMmEGiWU8zMJsVekYQf6kRUxI6Spk/5KkGheT9LPOztPDZk0eEE85wZ3eu1n4Spl0SBosUrvMBd5ruYBxnYuyzX9TmjaPqRoN13of4uV5+eDuCC+0cJ9Bz1vhB8lO/T9rZzu+DuIyIiwCzn8jjmONRrgilahiDCkweQZomex7T5ZU72y2PQQOO6bcfxSTvOCFFRo1dSGNhgiOfBYdHrBoAC33+MgXAHoo8+zgey9HBV//h1CjVHucvz4C3KAudaec5cX1gPYxDUZsRN4Ds2KFh8Cc=
  file: build/libs/*.jar
  file_glob: true
  skip_cleanup: true
  on:
    repo: ImyvmCircle/InvMenu
    tags: true